### PR TITLE
Team Kanaloa submission for VORC 2020/phase2

### PR DESCRIPTION
**Pull request by kvndngyn**

### CODE REVIEW

**Comment by crvogt** [comment]
@kvndngyn , thanks for your submission. As part of the submission process, we do a few checks to help you confirm that your submission is correct. Here are the results:

| Task  | Result | Notes |
| ----- | :------: | :------: |
Docker accessible | :green_circle:  	
stationkeeping | :red_circle: | :asterisk:  |
wayfinding | :red_circle: | :asterisk:  |  	
perception | :red_circle:  	
gymkhana | :red_circle:
 
Legend:
:green_circle: The behavior looks reasonable.
:yellow_circle:  The vessel shows activity but not necessary reasonable.
:red_circle: The vessel doesn't show any activity. 

:asterisk: **It appears that your code is publishing to WAMV topics, rather than CoRa. As well, you seem to be subscribed to VRX task topics rather than VORC as outlined [in the VORC Technical Guide](https://raw.githubusercontent.com/wiki/osrf/vorc/files/VORC2020_technical_guide_latest.pdf)** 

Please, let us know if you plan to tweak your submission or if you're happy with it as it is.

**Comment by kvndngyn** [comment]
I update the submission on Docker. We wanted to use this to learn Docker as it was an issue last time for us, so as long it is accessible, we will take that as our submission

**Comment by seankrag** [comment]
@kvndngyn, thank you for updating your submission. I have confirmed that your new docker image is accessible and now appears to utilize the VORC API described in the [VORC Technical Guide](https://github.com/osrf/vorc/wiki/files/VORC2020_technical_guide_latest.pdf)

| Task  | Result | Notes |
| ----- | :------: | :------: |
Docker accessible | :green_circle:  	
stationkeeping | :red_circle: | :asterisk:  |
wayfinding | :red_circle: | :asterisk:  |  	
perception | :red_circle: | :star: |
gymkhana | :red_circle: | :star: |

:asterisk: thrust commands are set to 0.0 for the entire task, and your console output indicates Station Keeping: False and Navigation: False. Perhaps you never begin your control algorithm?

:star: nothing is reported for perception. Were these tasks attempted?

Please let us know if you plan to tweak your submission further, or if you're happy with it as it is.

**Comment by kvndngyn** [comment]
We will proceed with this submission. I have learned a lot from VORC and hope that we can use this to better our submissions in the future

**Review by seankrag — APPROVED** [review]
Submission reviewed by @seankrag and @crvogt; feedback provided to Team Kanaloa. Team responded that they will proceed with latest submission as-is.

**Pull request merged**
