### PR TITLE
Team TheItalianJob phase II submission

### PR DESCRIPTION
**Pull request by glpuga**
The image repo is private but I added `virtualrobotx` as a collaborator. Let me know if that does not work.

Thanks!

### CODE REVIEW

**Comment by caguero** [comment]
@glpuga , thanks for your submission. As part of the submission process, we do a few checks to help you confirm that your submission is correct. Here are the results:

| Task                 |      Result      | Notes 
|---------------------|:-----------------:|---------:|
| Docker accessible |  🟢   |  |
| stationkeeping |  🟢   |  |
| wayfinding       |    🟢   |  |
| perception       | 🟢 |  |
| gymkhana       |    🟡   | In the obstacle course the vessel doesn't seem to go into the direction of the acoustic pinger |

Legend: 
🟢: The behavior looks reasonable.
🟡: The vessel shows activity but not necessary reasonable.
🔴: The vessel doesn't show any activity.

Please, let us know if you plan to tweak your submission or you're happy with it as it is.

**Comment by glpuga** [comment]
Thanks @caguero , I'll try to debug the issue later today. I'll let you know before the deadline if I can provide and updated version.

**Comment by glpuga** [comment]
Hi @caguero ! After looking into this I found that there are indeed some issues in my code that I would not be able to fix in time for the deadline, so I will not replace my current submission.

I did, however, notice some strange things while running my submission against most up to date commit of the `vorc` branch in  https://github.com/osrf/vrx-docker :

- My score (RMS error of the pose) on some of the stationkeeping runs is in excess of 5000 kilometers, way way larger than the size of the simulated world. I think that the problem is that  the generated xacros for runs 1 and 2 are pointed at Hawaii, e.g.:

`<xacro:stationkeeping lat="21.31099" lon="-157.88870" namespace="cora" heading="3" competition="vorc" >`

- Something similar happens in the wayfinding tasks. Except for run 0, all the rest of the xacros seem to send the ship on  tours somewhere just outside of Honolulu, e.g.:

`<waypoints>  <waypoint> <pose>21.31060  -157.88896 3</pose> </waypoint> <waypoint> <pose>21.31122  -157.88997 3.7</pose> </waypoint> <waypoint> <pose>21.31094  -157.89100 6</pose> </waypoint> <waypoint> <pose>21.31065  -157.88985 1</pose> </waypoint> <waypoint> <pose>21.31187 -157.88915 2</pose> </waypoint>  </waypoints>`

Regarding the note  "In the obstacle course the vessel doesn't seem to go into the direction of the acoustic pinger" in the first comment above, 

- For the Gymkhana, run 0, the vessel does indeed go to the position of the acoustic pinger after going through the channel, but the pinger seems to be located far away from the obstacle field, near a green marker. The `bearing_range` messages seem to agree with this. The score, however, seems to be calculated against the pose of the red pose marker within the obstacle field. Since the run is only 60 seconds long, the simulation ends when the vessel is just starting to move towards the pinger and away from the obstacle field.

- For Gymkhana runs 1 and 2 my vessel will not even attempt to go to the acoustic pinger because it becomes stuck trying to find the entrance to the obstacle course. This is on me, because I underestimated how far away from the channel entrance I could be spawned.

I did not create issues for these observations because I might be misinterpreting the `vrx-docker` tool configuration files and/or task scores, or there might be some other issue with my build. I'm just letting you know in case you think it's worth looking into this.

**Comment by mabelzhang** [comment]
> the generated xacros for runs 1 and 2 are pointed at Hawaii

Poking in, not hijacking thread, just responding in case others don't remember the status of this part.
What you're seeing for runs 1 and 2 is actually expected.
We only changed the numbers for run `0` in all the example tasks in `vrx-docker`. We intended to update runs > 0 to VORC coordinates but haven't done it yet (they still have TODO tags). For the actual competition, we will be using valid coordinates (I double-checked, thanks for reporting!).
The error is also larger because it's squared.

**Comment by glpuga** [comment]
> > the generated xacros for runs 1 and 2 are pointed at Hawaii
> 
> Poking in, not hijacking thread, just responding in case others don't remember the status of this part.
> What you're seeing for runs 1 and 2 is actually expected.
> We only changed the numbers for run `0` in all the example tasks in `vrx-docker`. We intended to update runs > 0 to VORC coordinates but haven't done it yet (they still have TODO tags). For the actual competition, we will be using valid coordinates (I double-checked, thanks for reporting!).
> The error is also larger because it's squared.

Thanks for the clarification @mabelzhang !

**Comment by caguero** [comment]
Submission reviewed; feedback provided to Team TheItalianJob. Team responded that they will proceed with latest submission as-is.

**Review by caguero — APPROVED** [review]

**Pull request merged**
