### PR TITLE
Team BumbleBee submission for VORC 2020/phase2

### PR DESCRIPTION
**Pull request by kaitlynng**

### CODE REVIEW

**Comment by seankrag** [comment]
@kaitlynng, thanks for your submission. As part of the submission process, we do a few checks to help you confirm that your submission is correct. Here are the results:

| Task                 |      Result      | Notes 
|---------------------|:-----------------:|---------:|
| Docker accessible |  🟢   |  |
| stationkeeping |  🟢   |  |
| wayfinding       |    🟢   |  |
| perception       | 🟡 |  |
| gymkhana       |    🟢   |  |

Legend: 
🟢: The behavior looks reasonable.
🟡: The vessel shows activity but task performance couldn't be verified.
🔴: The vessel doesn't show any activity.

Good luck in the competition!

**Review by seankrag — APPROVED** [review]

**Comment by kaitlynng** [comment]
Thank you very much! For the perception task, we're running a machine learning model to detect the objects, but we weren't able to verify that it was working with docker as we weren't receiving camera sensor messages from the simulation (could have been an issue on our part with the setting up of docker though). Is it possible for us to know what's the activity that the vessel is showing for the perception task?

Thanks for hosting the competition, VORC has been a great learning experience for us!

**Comment by seankrag** [comment]
@kaitlynng , sorry the "yellow stoplight" was a bit vague. During my checks, no message was published to /vorc/perception/landmark. After a little digging, your ML module appears to subscribe to /cora/sensors/cameras/front_left_camera/image_raw/compressed; however, the simulation is publishing camera images to /cora/sensors/cameras/front_left_camera/image_raw.

I'll pass this info along to the evaluation team.

**Comment by kaitlynng** [comment]
Ah I see, thank you! May I ask whether the compressed image topic will be published for the final evaluation?

**Comment by caguero** [comment]
hi @kaitlynng, your code is correct. The problem was on our side. We were not installing the `ros-melodic-compressed-image-transport` in the Docker image for the server. We'll expose that topic for the finals.

**Comment by kaitlynng** [comment]
Okay, thank you very much!

**Pull request merged**
