### PR TITLE
Orbit_ submission for VORC 2020/phase1

### PR DESCRIPTION
**Pull request by dag2104**

### CODE REVIEW

**Comment by caguero** [comment]
hi @dag2104 , thanks for your submission. Could you upload the video to Youtube, Vimeo, or any other public service and commit the URL instead?

**Comment by dag2104** [comment]
Oh ok I will place the link in the text file

**Comment by caguero** [comment]
Your submission is correct, thanks for the video and welcome to the VORC!

**Comment by dag2104** [comment]
So are we eligible for phase 2?
Because we don't received any mail saying the same thing.

**Comment by M1chaelM** [comment]
@dag2104 Yes, you are eligible. We sent an email to the contact we have associated with this team name, which is Ritika. If you'd prefer another point of contact just send us a message through the [contact form](https://www.oceanroboticschallenge.com/contact-us/) to let us know what it is.

**Comment by dag2104** [comment]
Thank you for your response.

**Pull request merged**
